# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: My Docs
theme:
  name: material
nav:
    - Home: index.md
    - Form: form.md
hooks:
  - docs/form.py
plugins:
  - search
